### ISSUE TITLE
State Machines

### ISSUE THREAD

**Issue by loklaan** [BrisJS/meetups#311] opened 2019-01-14 01:14 UTC
Requesting off the back of this [tweet by Ryan Florence](https://twitter.com/ryanflorence/status/1084248892072329216), which presents State Machines as easy to understand charts.

**Comment by iamkevinv** [comment] 2019-01-28 12:30
That's super cool @loklaan! From the title, i assumed you're not doing the talking, but you're keen to know if someone can jump in.... i can ask at the next meetup :)

**Comment by jwulf** [comment] 2019-05-14 02:47
I can talk about State Machines. I'm now working as Developer Advocate for Zeebe.io, which is... a state machine!

**Comment by loklaan** [comment] 2019-05-16 05:15
🙌 Awesome, I'd be stoked to see that talk Josh

**Comment by iamkevinv** [comment] 2019-07-01 09:28
@j1mr10rd4n has also volunteered!!

**Comment by MrCeleryman** [comment] 2019-07-03 08:58
We actually have just started our journey with creating and managing complex workflows with state machines and AWS Step Functions, happy to give some insight or do up some cool examples.

**Comment by jwulf** [comment] 2019-07-03 12:27
We could make the next BrisJS all about the State Machine.

**Comment by jwulf** [comment] 2019-07-19 06:33
Let's do this on August 5!

**Comment by j1mr10rd4n** [comment] 2019-07-19 10:18
I’m down with that! I've got most of a talk ready that might be a good kick-off point, it delves into the background and theory behind FSMs.

@jwulf, @MrCeleryman - let me know if you want a peek at the slides/text, or maybe a face-to-face catchup beforehand, for smooth segues!

**Comment by iamkevinv** [comment] 2019-07-31 13:31
@jwulf @j1mr10rd4n @MrCeleryman - Are you confirmed to speak on Monday? I'm excited to see a team talk!

**Comment by j1mr10rd4n** [comment] 2019-08-01 03:59
i'm (mostly) ready! i haven't heard any more from @jwulf or @MrCeleryman...

**Comment by iamkevinv** [comment] 2019-08-01 04:05
Hopefully they respond soon @j1mr10rd4n - I'll confirm this talk is happening either way. Thanks.

**Comment by jwulf** [comment] 2019-08-01 12:04
20 minutes for three people? That seems pretty lean...

**Comment by iamkevinv** [comment] 2019-08-01 12:14
lol yeah that's a potential oversight. 30 min it is.

**Comment by iamkevinv** [comment] 2019-08-01 12:19
I'll be timing though - need to keep a strict lid on talks to keep things fair and equitable for all speakers :)

**Comment by j1mr10rd4n** [comment] 2019-08-02 04:34
@iamkevinv the https://brisjs.org front page has the date of the next talk as 1st August, should be the 5th

**Comment by iamkevinv** [comment] 2019-08-02 04:55
> @iamkevinv the https://brisjs.org front page has the date of the next talk as 1st August, should be the 5th

Yeah you’re right looks like it’s not parsing the date on the meetup api field correctly. Thanks.

**Comment by jwulf** [comment] 2019-08-07 02:37
Here is a link to my demo: https://github.com/jwulf/zeebe-ecommerce-demo

**Comment by iamkevinv** [comment] 2020-02-24 12:51
Thanks for your talks folks! I'm cleaning up and closing the issue.

**Closed** 2020-02-24 12:51 UTC
Labels: Resources Shared
