### ISSUE TITLE
TDD by example using Node and Mocha

### ISSUE THREAD

**Issue by eddieajau** [BrisJS/meetups#10] opened 2014-06-03 23:53 UTC
Coming from a strong TDD heritage in PHP, I could probably share what I've learned to recreate a testing stack based on TDD principles that is more familiar to the classical programmer than BDD testing (which, to me, is analogous to Integration Testing).

**Comment by eddieajau** [comment] 2015-02-16 22:42
Still working on it. Thanks for your patience :)

**Comment by iamkevinv** [comment] 2015-06-16 11:00
Ping v2? :)

**Comment by eddieajau** [comment] 2015-06-16 22:30
Didn't you have a talk on that already? If you still want this I could do it for August? It'd cut straight to code examples since we've already had a talk on the philosophical reasons why to use TDD.

**Comment by iamkevinv** [comment] 2015-06-29 12:11
Yes we did @eddieajau. @marklawlor did a good job introducing it - and was going to look at implementation in his next talk. Perhaps yourself and mark can have a quick comparison and see who wants to do what, or even do a team talk.

**Comment by eddieajau** [comment] 2015-06-29 23:24
@marklawlor do you want to shoot me an email via meetup or [here](http://eddify.me/contact.html)? @iamkevinv would a 1 hour slot be out of the question because it's very difficult to go deep into examples in just 15 mins?

**Comment by marklawlor** [comment] 2015-06-30 13:08
@eddieajau I'm not to sure if you saw my first talk on TDD, it was mostly about the merits of TDD and how I believe it improves a teams workflow. I think an actual talk with examples would be great

My second talk was going to be a quick example project showing how to build a small library with the TDD philosophy. I mostly wanted to show how TDD isn't just for monolithic projects, and is just a workflow and can be used for anything.  But, that never happened as I had to travel for family stuff.

I haven't volunteered the talk again because I've come to the conclusion that talks where you watch someone else code for 15mins are boring talks. So I've been thinking of other ways to present that are more engaging

I'm happy to help out / do a team talk, and I'm interested on your ideas for presenting. It might be easier to chat via gitter instead of email https://gitter.im/marklawlor

**Comment by garrows** [comment] 2015-06-30 20:05
I dont think they are boring @marklawlor :-/
I've been looking forward to your follow up talk too so dont take too long.

**Comment by eddieajau** [comment] 2015-06-30 20:58
Ok, I'm happy to commit to a slot, and I'll talk to Mark about it on the side. 30-45 mins would be good because watching the steps of TDD is actually more important than just looking at the final product.

Mark, I'd mostly be gleaning from the way Robert Martin teaches TDD and pick a simple example and to the red-green-refactor process using Mocha in Node. I'd want to try to fit in an example of using Supertest for a simple Express app, and try to fit in some examples for using (sparingly) spies and other test doubles. As I'm going through things, I'd also try and point out the difference between unit, integration and functional tests. I won't, however, be covering testing in the browser.

**Comment by iamkevinv** [comment] 2015-07-28 13:23
I didn't really hear if this is confirmed for Aug 3rd so i've left it off... however we will have time to add it to the line up still and i can send a supplemental announcement in a few days. Please let me know if its Aug or Sept folks :)

**Comment by iamkevinv** [comment] 2015-10-26 04:37
@eddieajau @marklawlor - Did either of you guys have the presentations ready for presenting? Next one is Nov 2

**Comment by eddieajau** [comment] 2015-10-26 22:02
Hi Kevin. I'm very sorry but I'm in the process of moving up to the sunny coast atm. Might have to make it next year.

**Comment by iamkevinv** [comment] 2015-11-30 11:07
@marklawlor - did you get any time to set up a small presentation?

**Comment by AshKyd** [comment] 2016-01-12 10:31
@eddieajau Hope the move went well. I'm keen to line you up for the February meetup, reckon you'll be able to make it?

**Comment by iamkevinv** [comment] 2016-06-08 10:30
@eddieajau - This a possibility for the future? Otherwise i'm happy to close it.

**Comment by eddieajau** [comment] 2016-06-09 11:48
Yes, happy to lock it in for the July meetup or later.

**Comment by iamkevinv** [comment] 2016-06-12 03:01
Consider that locked for July

**Comment by eddieajau** [comment] 2016-06-12 22:09
Ok. How long is the time slot?

**Comment by iamkevinv** [comment] 2016-06-13 01:25
20 mins or 40 minutes are the usual selections.

**Comment by eddieajau** [comment] 2016-06-13 04:06
Do you want me to plan for 40, and I can always cut it back if there are other good offers?

**Comment by iamkevinv** [comment] 2016-06-13 06:48
You are more than welcome to ask for any amount you like :-)
We will hopefully have quite a few things come up for July, but i'm always happier to have more content than too little.

**Comment by eddieajau** [comment] 2016-06-27 09:05
Ok. For the talk let's just call it "TDD by example using Node and Mocha". I'll work through a simple example from scratch using TDD and we'll see how far we get.

**Comment by iamkevinv** [comment] 2016-06-28 13:18
Looking forward to your 40min slot first up at our July meetup :) thanks @eddieajau

**Comment by iamkevinv** [comment] 2016-07-14 09:04
Thanks again for the talk @eddieajau - if you can share resources / links here that would be good.

**Comment by iamkevinv** [comment] 2016-11-01 12:28
Any resources you can share @eddieajau? I'll close this issue for now, but don't let that stop you :) Thanks!

**Closed by iamkevinv** 2016-11-01 12:28 UTC
Labels: Talk Done - Pending Resources
