### ISSUE TITLE
Contract - Angular Freelance - Project Managment Platform

### ISSUE THREAD

**Issue by Lexvancooten** [BrisJS/meetups#333] opened 2019-04-24 06:02 UTC
About The Role
We are looking for a freelance Angular developer to work on updating a current project. The project is a Project Management Platform which has been built using Angular 1.0. Happy for you to work remote (we are based in Brisbane), a portfolio demonstrating examples of your previous work as a freelancer is required and it is preferable that you have had at least 2 years experience. If any further information is required please let me know, happy to clarify any further details you may need. You can emial me directly at Lex@ImmerseEnterprise.com

**Comment by iamkevinv** [comment] 2019-05-07 18:54
Duplicate of #332

**Closed** 2019-05-07 18:54 UTC
